spring.application.name=digital-wallet
spring.datasource.url=jdbc:mysql://localhost:3306/digital_wallet
spring.datasource.username=root
spring.datasource.password=DigitalBank@123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8081
